# Какая часть ВСЕХ предметов из инвентаря остаётся у игрока после смерти.
# Остальная часть выпадет на землю.
# 0.50 = сохраняется 50%, выпадает 50%
keep-percent: 0.50

# На сколько процентов от максимальной прочности повреждаются ВСЕ предметы,
# у которых есть механика прочности (инструменты, броня, элитры и т.д.).
# Если после этого предмет достигает предела прочности, он ломается и исчезает.
durability-damage-percent: 0.10

# Отправлять ли игроку сообщение после смерти
send-message: true

messages:
  death-summary: "&cПри смерти выпало &e%dropped% &cпредмет(ов), сохранилось &a%kept%&c, а &6%broken% &cсломалось от прочности."
